# Generated by Django 4.2.16 on 2024-10-25 00:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('uuid_imagem', models.UUIDField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_nascimento', models.DateField()),
                ('nick', models.TextField(max_length=20, unique=True)),
                ('nome', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.feed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to='api.user')),
                ('seguindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
